# Generated by Django 3.2.9 on 2023-01-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220819_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='cover',
            field=models.ImageField(default='/static/images/dfault.png', upload_to='title_covers/'),
        ),
        migrations.AddField(
            model_name='title',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'User'), ('1', 'actor'), ('2', 'director'), ('3', 'writer')], default='0', max_length=16),
        ),
    ]
