# Generated by Django 3.2.9 on 2023-04-14 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230414_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='stars',
            field=models.ManyToManyField(related_name='titles_starred', to=settings.AUTH_USER_MODEL),
        ),
    ]
