# Generated by Django 3.2.9 on 2023-01-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230103_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='title_banners/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='cover',
            field=models.ImageField(default='media/title_covers/default.png', upload_to='title_covers/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='title', to='backend.Tag'),
        ),
    ]
