# Generated by Django 3.2.9 on 2023-01-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230104_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='is_popular',
            new_name='popular',
        ),
    ]
