# Generated by Django 3.2.9 on 2023-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_is_popular_title_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='cover',
            field=models.ImageField(default='/title_covers/default.png', upload_to='title_covers/'),
        ),
    ]
