# Generated by Django 3.2.9 on 2023-01-20 17:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_title_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='banner',
            field=models.ImageField(blank=True, default='/title_banners/default.jpeg', null=True, upload_to='title_banners/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))]),
        ),
        migrations.AlterField(
            model_name='title',
            name='titleType',
            field=models.CharField(choices=[('M', 'Movie'), ('TV', 'TVSeries'), ('EP', 'TVEpisode')], max_length=16),
        ),
    ]
